// Code generated by "gends"; DO NOT EDIT.

package stack // import "kkn.fi/stack"

// ByteStack is a stack data structure.
type ByteStack []byte

// NewByte creates an empty byte stack.
func NewByte() *ByteStack {
	return &ByteStack{}
}

// Push a value to stack
func (s *ByteStack) Push(value byte) {
	(*s) = append([]byte{value}, (*s)...)
}

// Pop removes the most recently added item
func (s *ByteStack) Pop() byte {
	value := (*s)[0]
	(*s) = (*s)[1:]
	return value
}

// Slice returns the stack contents as an byte slice.
func (s *ByteStack) Slice() []byte {
	return []byte(*s)
}

// Peek returns the most recently added item.
func (s *ByteStack) Peek() byte {
	return (*s)[0]
}

// IsEmpty returns true if the stack is empty.
func (s *ByteStack) IsEmpty() bool {
	return len(*s) == 0
}

// Len returns the number of items in the stack.
func (s *ByteStack) Len() int {
	return len(*s)
}
