// Code generated by "gends"; DO NOT EDIT.

package stack // import "kkn.fi/stack"

// Float64Stack is a stack data structure.
type Float64Stack []float64

// NewFloat64 creates an empty float64 stack.
func NewFloat64() *Float64Stack {
	return &Float64Stack{}
}

// Push a value to stack
func (s *Float64Stack) Push(value float64) {
	(*s) = append([]float64{value}, (*s)...)
}

// Pop removes the most recently added item
func (s *Float64Stack) Pop() float64 {
	value := (*s)[0]
	(*s) = (*s)[1:]
	return value
}

// Slice returns the stack contents as an float64 slice.
func (s *Float64Stack) Slice() []float64 {
	return []float64(*s)
}

// Peek returns the most recently added item.
func (s *Float64Stack) Peek() float64 {
	return (*s)[0]
}

// IsEmpty returns true if the stack is empty.
func (s *Float64Stack) IsEmpty() bool {
	return len(*s) == 0
}

// Len returns the number of items in the stack.
func (s *Float64Stack) Len() int {
	return len(*s)
}
