// Code generated by "gends"; DO NOT EDIT.

package stack // import "kkn.fi/stack"

// Float32Stack is a stack data structure.
type Float32Stack []float32

// NewFloat32 creates an empty float32 stack.
func NewFloat32() *Float32Stack {
	return &Float32Stack{}
}

// Push a value to stack
func (s *Float32Stack) Push(value float32) {
	(*s) = append([]float32{value}, (*s)...)
}

// Pop removes the most recently added item
func (s *Float32Stack) Pop() float32 {
	value := (*s)[0]
	(*s) = (*s)[1:]
	return value
}

// Slice returns the stack contents as an float32 slice.
func (s *Float32Stack) Slice() []float32 {
	return []float32(*s)
}

// Peek returns the most recently added item.
func (s *Float32Stack) Peek() float32 {
	return (*s)[0]
}

// IsEmpty returns true if the stack is empty.
func (s *Float32Stack) IsEmpty() bool {
	return len(*s) == 0
}

// Len returns the number of items in the stack.
func (s *Float32Stack) Len() int {
	return len(*s)
}
