// Code generated by "gends"; DO NOT EDIT.

package stack // import "kkn.fi/stack"

// Int32Stack is a stack data structure.
type Int32Stack []int32

// NewInt32 creates an empty int32 stack.
func NewInt32() *Int32Stack {
	return &Int32Stack{}
}

// Push a value to the stack.
func (s *Int32Stack) Push(value int32) {
	(*s) = append([]int32{value}, (*s)...)
}

// Pop removes the most recently added item.
// If called on an empty stack will return ErrEmptyStack error.
func (s *Int32Stack) Pop() (int32, error) {
	if len(*s) == 0 {
		return 0, ErrEmptyStack
	}
	value := (*s)[0]
	(*s) = (*s)[1:]
	return value, nil
}

// Slice returns the stack contents as a slice of int32's.
func (s *Int32Stack) Slice() []int32 {
	return []int32(*s)
}

// Peek returns the most recently added item.
// If called on an empty stack will return ErrEmptyStack error.
func (s *Int32Stack) Peek() (int32, error) {
	if len(*s) == 0 {
		return 0, ErrEmptyStack
	}
	return (*s)[0], nil
}

// IsEmpty returns true if the stack is empty.
func (s *Int32Stack) IsEmpty() bool {
	return len(*s) == 0
}

// Len returns the number of items in the stack.
func (s *Int32Stack) Len() int {
	return len(*s)
}
