// Code generated by "gends"; DO NOT EDIT.

package stack // import "kkn.fi/stack"

// Int32Stack is a stack data structure.
type Int32Stack []int32

// NewInt32 creates an empty int32 stack.
func NewInt32() *Int32Stack {
	return &Int32Stack{}
}

// Push a value to stack
func (s *Int32Stack) Push(value int32) {
	(*s) = append([]int32{value}, (*s)...)
}

// Pop removes the most recently added item
func (s *Int32Stack) Pop() int32 {
	value := (*s)[0]
	(*s) = (*s)[1:]
	return value
}

// Slice returns the stack contents as an int32 slice.
func (s *Int32Stack) Slice() []int32 {
	return []int32(*s)
}

// Peek returns the most recently added item.
func (s *Int32Stack) Peek() int32 {
	return (*s)[0]
}

// IsEmpty returns true if the stack is empty.
func (s *Int32Stack) IsEmpty() bool {
	return len(*s) == 0
}

// Len returns the number of items in the stack.
func (s *Int32Stack) Len() int {
	return len(*s)
}
