// Code generated by "gends"; DO NOT EDIT.

package stack // import "kkn.fi/stack"

// Int64 is a stack data structure.
type Int64 []int64

// NewInt64 creates an empty int64 stack.
func NewInt64() *Int64 {
	return &Int64{}
}

// Push a value to the stack.
func (s *Int64) Push(value int64) {
	(*s) = append([]int64{value}, (*s)...)
}

// Pop removes the most recently added item.
// If called on an empty stack will return ErrEmptyStack error.
func (s *Int64) Pop() (int64, error) {
	if len(*s) == 0 {
		return 0, ErrEmptyStack
	}
	value := (*s)[0]
	(*s) = (*s)[1:]
	return value, nil
}

// Slice returns the stack contents as a slice of int64's.
func (s *Int64) Slice() []int64 {
	return []int64(*s)
}

// Peek returns the most recently added item.
// If called on an empty stack will return ErrEmptyStack error.
func (s *Int64) Peek() (int64, error) {
	if len(*s) == 0 {
		return 0, ErrEmptyStack
	}
	return (*s)[0], nil
}

// IsEmpty returns true if the stack is empty.
func (s *Int64) IsEmpty() bool {
	return len(*s) == 0
}

// Len returns the number of items in the stack.
func (s *Int64) Len() int {
	return len(*s)
}
