// Code generated by "gends"; DO NOT EDIT.

package stack // import "kkn.fi/stack"

// Int64Stack is a stack data structure.
type Int64Stack []int64

// NewInt64 creates an empty int64 stack.
func NewInt64() *Int64Stack {
	return &Int64Stack{}
}

// Push a value to stack
func (s *Int64Stack) Push(value int64) {
	(*s) = append([]int64{value}, (*s)...)
}

// Pop removes the most recently added item
func (s *Int64Stack) Pop() int64 {
	value := (*s)[0]
	(*s) = (*s)[1:]
	return value
}

// Slice returns the stack contents as an int64 slice.
func (s *Int64Stack) Slice() []int64 {
	return []int64(*s)
}

// Peek returns the most recently added item.
func (s *Int64Stack) Peek() int64 {
	return (*s)[0]
}

// IsEmpty returns true if the stack is empty.
func (s *Int64Stack) IsEmpty() bool {
	return len(*s) == 0
}

// Len returns the number of items in the stack.
func (s *Int64Stack) Len() int {
	return len(*s)
}
