// Code generated by "gends"; DO NOT EDIT.

package stack // import "kkn.fi/stack"

// Int8 is a stack data structure.
type Int8 []int8

// NewInt8 creates an empty int8 stack.
func NewInt8() *Int8 {
	return &Int8{}
}

// Push a value to the stack.
func (s *Int8) Push(value int8) {
	(*s) = append([]int8{value}, (*s)...)
}

// Pop removes the most recently added item.
// If called on an empty stack will return ErrEmptyStack error.
func (s *Int8) Pop() (int8, error) {
	if len(*s) == 0 {
		return 0, ErrEmptyStack
	}
	value := (*s)[0]
	(*s) = (*s)[1:]
	return value, nil
}

// Slice returns the stack contents as a slice of int8's.
func (s *Int8) Slice() []int8 {
	return []int8(*s)
}

// Peek returns the most recently added item.
// If called on an empty stack will return ErrEmptyStack error.
func (s *Int8) Peek() (int8, error) {
	if len(*s) == 0 {
		return 0, ErrEmptyStack
	}
	return (*s)[0], nil
}

// IsEmpty returns true if the stack is empty.
func (s *Int8) IsEmpty() bool {
	return len(*s) == 0
}

// Len returns the number of items in the stack.
func (s *Int8) Len() int {
	return len(*s)
}
