// Code generated by "gends"; DO NOT EDIT.

package stack // import "kkn.fi/stack"

// Int8Stack is a stack data structure.
type Int8Stack []int8

// NewInt8 creates an empty int8 stack.
func NewInt8() *Int8Stack {
	return &Int8Stack{}
}

// Push a value to stack
func (s *Int8Stack) Push(value int8) {
	(*s) = append([]int8{value}, (*s)...)
}

// Pop removes the most recently added item
func (s *Int8Stack) Pop() int8 {
	value := (*s)[0]
	(*s) = (*s)[1:]
	return value
}

// Slice returns the stack contents as an int8 slice.
func (s *Int8Stack) Slice() []int8 {
	return []int8(*s)
}

// Peek returns the most recently added item.
func (s *Int8Stack) Peek() int8 {
	return (*s)[0]
}

// IsEmpty returns true if the stack is empty.
func (s *Int8Stack) IsEmpty() bool {
	return len(*s) == 0
}

// Len returns the number of items in the stack.
func (s *Int8Stack) Len() int {
	return len(*s)
}
