// Code generated by "gends"; DO NOT EDIT.

package stack // import "kkn.fi/stack"

// RuneStack is a stack data structure.
type RuneStack []rune

// NewRune creates an empty rune stack.
func NewRune() *RuneStack {
	return &RuneStack{}
}

// Push a value to the stack.
func (s *RuneStack) Push(value rune) {
	(*s) = append([]rune{value}, (*s)...)
}

// Pop removes the most recently added item.
// If called on an empty stack will return ErrEmptyStack error.
func (s *RuneStack) Pop() (rune, error) {
	if len(*s) == 0 {
		return 0, ErrEmptyStack
	}
	value := (*s)[0]
	(*s) = (*s)[1:]
	return value, nil
}

// Slice returns the stack contents as a slice of rune's.
func (s *RuneStack) Slice() []rune {
	return []rune(*s)
}

// Peek returns the most recently added item.
// If called on an empty stack will return ErrEmptyStack error.
func (s *RuneStack) Peek() (rune, error) {
	if len(*s) == 0 {
		return 0, ErrEmptyStack
	}
	return (*s)[0], nil
}

// IsEmpty returns true if the stack is empty.
func (s *RuneStack) IsEmpty() bool {
	return len(*s) == 0
}

// Len returns the number of items in the stack.
func (s *RuneStack) Len() int {
	return len(*s)
}
