// Code generated by "gends"; DO NOT EDIT.

package stack // import "kkn.fi/stack"

// Uint8Stack is a stack data structure.
type Uint8Stack []uint8

// NewUint8 creates an empty uint8 stack.
func NewUint8() *Uint8Stack {
	return &Uint8Stack{}
}

// Push a value to the stack.
func (s *Uint8Stack) Push(value uint8) {
	(*s) = append([]uint8{value}, (*s)...)
}

// Pop removes the most recently added item.
// If called on an empty stack will return ErrEmptyStack error.
func (s *Uint8Stack) Pop() (uint8, error) {
	if len(*s) == 0 {
		return 0, ErrEmptyStack
	}
	value := (*s)[0]
	(*s) = (*s)[1:]
	return value, nil
}

// Slice returns the stack contents as a slice of uint8's.
func (s *Uint8Stack) Slice() []uint8 {
	return []uint8(*s)
}

// Peek returns the most recently added item.
// If called on an empty stack will return ErrEmptyStack error.
func (s *Uint8Stack) Peek() (uint8, error) {
	if len(*s) == 0 {
		return 0, ErrEmptyStack
	}
	return (*s)[0], nil
}

// IsEmpty returns true if the stack is empty.
func (s *Uint8Stack) IsEmpty() bool {
	return len(*s) == 0
}

// Len returns the number of items in the stack.
func (s *Uint8Stack) Len() int {
	return len(*s)
}
