// Code generated by "gends"; DO NOT EDIT.

package stack // import "kkn.fi/stack"

// Uint64Stack is a stack data structure.
type Uint64Stack []uint64

// NewUint64 creates an empty uint64 stack.
func NewUint64() *Uint64Stack {
	return &Uint64Stack{}
}

// Push a value to stack
func (s *Uint64Stack) Push(value uint64) {
	(*s) = append([]uint64{value}, (*s)...)
}

// Pop removes the most recently added item
func (s *Uint64Stack) Pop() uint64 {
	value := (*s)[0]
	(*s) = (*s)[1:]
	return value
}

// Slice returns the stack contents as an uint64 slice.
func (s *Uint64Stack) Slice() []uint64 {
	return []uint64(*s)
}

// Peek returns the most recently added item.
func (s *Uint64Stack) Peek() uint64 {
	return (*s)[0]
}

// IsEmpty returns true if the stack is empty.
func (s *Uint64Stack) IsEmpty() bool {
	return len(*s) == 0
}

// Len returns the number of items in the stack.
func (s *Uint64Stack) Len() int {
	return len(*s)
}
